### PR TITLE
Typo on Poimandres

### PR DESCRIPTION
**Pull request by dbismut**
I'm maintaining react-use-gesture. Happy to see this lib grow on Vue but I'd appreciate if you mention right away that this is a port of the lib, on top of the Read Me. I'd also appreciate if you could use a different color scheme for the documentation website. This is not urgent, take your time, and if you don't want to, so be it ;)

### CODE REVIEW

**Comment by koca** [comment]
Hey @dbismut, thanks for the PR. 

> I'd appreciate if you mention right away
 
i guess i did? it's in the [readme](https://github.com/koca/vue-use-gesture/blob/main/README.md#thanks) & website & [tweet](https://twitter.com/imesutkoca/status/1369370874235731976?s=20)

> I'd also appreciate if you could use a different color scheme for the documentation

Could you elaborate? its not readable or something?

**Comment by dbismut** [comment]
> i guess i did? it's in the readme & website & tweet

I meant on **top** of the ReadMe.

> Could you elaborate? its not readable or something?

Too close to react-use-gesture current identity.

**Comment by koca** [comment]
> I meant on **top** of the ReadMe.

oh, sure.

> Too close to react-use-gesture current identity.

I can use teal instead of yellow/orange color for the logo etc sounds good? Or do you have an idea?

**Comment by dbismut** [comment]
> I can use teal instead of yellow/orange for the logo etc sounds good? Or do you have an idea?

It's just that all css vars from the website: the blue, the yellow feel really identical. Anyway no major deal, if you want to keep it like this, no worries.

**Comment by koca** [comment]
> > I can use teal instead of yellow/orange for the logo etc sounds good? Or do you have an idea?
> 
> It's just that all css vars from the website: the blue, the yellow feel really identical. Anyway no major deal, if you want to keep it like this, no worries.

that was the point actually, this is not my library its react-use-gesture's code. We use react-use-gesture for our react projects and we needed for one of our vue project. That's why i built it. I wanted to keep the api, look and feel the same as react-use-gesture. I dont mind removing this repo if you want to collabarate on making a framework agnostic use-gesture repo :D but anyways i'll change the colors. Even if i change the blues etc. u'll feel the same. Im a core team member of chakraui so take a look at https://chakra-ui.com/docs/getting-started (with dark mode enabled) its the same colors as react-use-gesture? :D even though its not exactly the same hex but it would feel the same. So, sorry about that :D

**Comment by dbismut** [comment]
No problem really! Interesting though, we could try to make use-gesture platform agnostic or rather provide plugins for React, Vue, you name it. Only hooks are React specific 90% of the lib is universal. Let's discuss that further, I want to work on v10 next month, would be cool to have you on board to see how we could make this work on vue as well?

Like:

```js
import { useDrag } from "@use-gesture/react"
```

Cheers!

**Comment by koca** [comment]
@dbismut Exactly! . Yea the core stuff is almost framework agnostic so it wouldnt be that hard. We can do it ^^ Just let me know when you have time. 

> 
> Like:
> 
> ```js
> import { useDrag } from "@use-gesture/react"
> ```

💯 love the api already :)

I can give you my twitter username or discord which one would you prefer?

**Comment by dbismut** [comment]
Can you join pmndrs discord? The room is react-use-gesture let's catch up in there!

**Comment by koca** [comment]
oh youre right! im already in there joined months ago :)

**Pull request merged**
